pipeline{
    agent{
        label "nodejs"
    }
	stages{
        stage('Deploy') {
            steps {
                sh '''
                    oc project puuxlq--deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
